[package]
name = "rust-backend-scaffolder"
version = "0.1.0"
edition = "2024"
authors = ["Abel Osaretin <contact.abel321@gmail.com>, Jude Abara <judeabara@gmail,com>"]

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
